-- Create relationships section ------------------------------------------------- 

ALTER TABLE `Product` ADD CONSTRAINT `belongs to` FOREIGN KEY (`Group_ID`) REFERENCES `Product Group` (`Group_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Product` ADD CONSTRAINT `supplies` FOREIGN KEY (`Supplier_ID`) REFERENCES `Supplier` (`Supplier_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Product` ADD CONSTRAINT `are given` FOREIGN KEY (`Review_ID`) REFERENCES `Reviews` (`Review_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Bill` ADD CONSTRAINT `is included` FOREIGN KEY (`Voucher_ID`) REFERENCES `Voucher` (`Voucher_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Address` ADD CONSTRAINT `will have` FOREIGN KEY (`Customer_ID`) REFERENCES `Customer` (`Customer_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Zip Code` ADD CONSTRAINT `will zip` FOREIGN KEY (`Address_ID`) REFERENCES `Address` (`Address_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Employees` ADD CONSTRAINT `monitors` FOREIGN KEY (`Payment_ID`) REFERENCES `Payment` (`Payment_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Bill` ADD CONSTRAINT `Generates` FOREIGN KEY (`Payment_ID`) REFERENCES `Payment` (`Payment_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Payment` ADD CONSTRAINT `makes` FOREIGN KEY (`Customer_ID`) REFERENCES `Customer` (`Customer_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Order Product` ADD CONSTRAINT `product order relation` FOREIGN KEY (`Product_ID`) REFERENCES `Product` (`Product_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Order Product` ADD CONSTRAINT `contains` FOREIGN KEY (`Order_ID`) REFERENCES `Orders` (`Order_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Orders` ADD CONSTRAINT `Orders` FOREIGN KEY (`Payment_ID`) REFERENCES `Payment` (`Payment_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Bill` ADD CONSTRAINT `is billed` FOREIGN KEY (`Order_ID`) REFERENCES `Orders` (`Order_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Product Details` ADD CONSTRAINT `has details` FOREIGN KEY (`Product_ID`) REFERENCES `Product` (`Product_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE `Customer Category` ADD CONSTRAINT `belong` FOREIGN KEY (`Customer_ID`) REFERENCES `Customer` (`Customer_ID`) ON DELETE RESTRICT ON UPDATE RESTRICT
;